import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "@/globals.css";
import clsx from "clsx";
import { IlPepe } from "@/assets";
import LayoutHeader from "@/components/LayoutHeader";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "fixed inset-0 flex flex-col overflow-y-scroll"
        )}
      >
        <div className="z-0 flex-1 flex flex-col space-y-8 pb-64 bg-gradient-to-b from-green-700 overflow-y-scroll md:pb-0">
          <LayoutHeader />
          {children}
        </div>
        <IlPepe
          alt="Pepe Logo"
          className="-z-10 absolute -left-8 -bottom-10"
          width={256}
          style={{ transform: "scaleX(-1)" }}
        />
      </body>
    </html>
  );
}
