import type { Metadata, Viewport } from "next";
import { Montserrat } from "next/font/google";

import "@/globals.css";
import clsx from "clsx";
import { IlPepe } from "@/assets";
import LayoutHeader from "@/components/LayoutHeader";
import LayoutFooter from "@/components/LayoutFooter";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#22c55e"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "fixed inset-0 flex flex-col overflow-y-scroll"
        )}
      >
        <div className="z-0 flex-1 flex flex-col space-y-32 bg-gradient-to-b from-green-700 overflow-y-scroll">
          <div className="flex-1 flex flex-col space-y-8">
            <LayoutHeader />
            {children}
          </div>
          <LayoutFooter />
        </div>
      </body>
    </html>
  );
}
